Repository darkrockmountain/gomail, pull requests merged in 2024-06, with the labels that each got.

#18 fix(ci): pin FOSSA Action to a specific commit hash
  .github/workflows/fossa.yaml
Labels: bug, dependencies

#26 fix: replace deprecated ioutil.ReadFile with os.ReadFile
  email_sender.go
Labels: bug, dependencies, deprecated

#37 docs(examples): fix errors and add Prerequisites section in README files
  .examples/serverless/digitalocean_functions/README.md
Labels: documentation

#38 docs: fix minor documentation issues for uniformity with godoc
  .examples/serverless/azure_functions/azure_email_sender.go
  common/attachment.go
  common/attachment_test.go
  common/doc.go
  common/email.go
  common/utils.go
  common/utils_test.go
  common/validation_test.go
  credentials/helpers.go
  gomail.go
  providers/doc.go
  providers/gmail/gmail_email_sender.go
  providers/smtp/smtp_email_sender.go
  sanitizer/default_html_sanitizer.go
  sanitizer/default_text_sanitizer.go
  sanitizer/non_sanitizer.go
  sanitizer/sanitizer_func.go
  sanitizer/sanitizer_func_test.go
Labels: documentation
